FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install

# the copy is not really necessary in dev as we are attaching sources as a volume but you can keep it if you want
#COPY . .

CMD ["npm", "run", "dev"]